version: '3.1'
services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - MONGO_URL=mongodb://db/youOweMeMoney
  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=youOweMeMoney
